### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by hbendev** [mnik01/rendering-modes#2]
### Clear and concise description of the problem

Thanks! This indeed works on storybook v8+. I don't understand why something like this is not a default feature.

### Suggested solution

I recommend mentioning in the readme that this is also a replacement for `@jeysal/storybook-addon-css-user-preferences@0.0.2` and below.

### Reproduction

None

### System Info

```Shell
`"storybook": "^8.2.9",`
```

### Used Package Manager

pnpm

**Comment by mnik01** [comment]
Hello. Thanks.
Introduced in this commit https://github.com/mnik01/rendering-modes/commit/7665675e78c9b19221dfdc6db23fc877a36f19e9
